# Gemfile
source 'https://rubygems.org'

gem 'sinatra'
gem 'mongoid'
# Required to use some advanced features of# Sinatra, like namespaces
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'graphql'
